### ISSUE TITLE
Duplicated styles in org-default.css

### ISSUE THREAD

**Issue by pcr910303** [gongzhitaao/orgcss#10]
In [org-default.css](https://github.com/gongzhitaao/orgcss/blob/e422734d9df73183ba5a08dc698145fa4a79eba0/src/css/org-default.css), [Lines 3-560](https://github.com/gongzhitaao/orgcss/blob/e422734d9df73183ba5a08dc698145fa4a79eba0/src/css/org-default.css#L3-L560) and [Lines 569-1126](https://github.com/gongzhitaao/orgcss/blob/e422734d9df73183ba5a08dc698145fa4a79eba0/src/css/org-default.css#L569-L1126) are exactly the same.

Is it for browser compatibility or something similar? The [hosted version](https://gongzhitaao.org/orgcss/org.css) looks like the rules are removed while minifying: is this expected behavior? Should the duplicate lines be removed?

**Comment by gongzhitaao** [comment]
Hello @pcr910303 Good catch and thanks for the PR.  I didn't notice this.  It might be because of some flags in Emacs when exporting this CSS.  I will double-check my Emacs configuration.  As for the PR, this file is automatically generated by Emacs, so I would prefer to regenerate it instead of manually edit it.

Besides, this duplicate will be removed by the minifier :smile:

**Comment by pcr910303** [comment]
@gongzhitaao Okay, will be waiting for the fix! 👍

**Comment by gongzhitaao** [comment]
Thank you! Got it fixed in 93cf27968ffbb28253875074c1a97087d2f8c24b
